Sprint2
Iker-elorrieta/ADT1 pull request #2
Opened 2021-11-02 08:06 UTC by Unai-GarciaGi

2021-11-02 10:53 UTC, Iker-elorrieta requested changes
![image](https://user-images.githubusercontent.com/71759245/139832835-82a0fb55-b8ee-4ac6-80bc-96eba9e90c21.png)
Fallan varios test, ¿Es esto normal?

El tema de la introducción de libros solo en archivo, a revisar de cara al siguiente sprint

2021-11-02 10:53 UTC, Iker-elorrieta commented on AccesoADatos_Reto1/src/lectores/LectorTxt.java
> +							lib.setNotas(lib.getNotas() + ":" + texto);
los : puntos

2021-11-02 17:27 UTC, Unai-GarciaGi commented on AccesoADatos_Reto1/src/lectores/LectorTxt.java
> +							lib.setNotas(lib.getNotas() + ":" + texto);
Corregido

Sobre la introducción en archivo: ahora también se introducen en el array, la opción sigue existiendo, porque nos parece útil, pero primero se colocará en el array

Sobre los tests: los tests dan bien si se hacen de uno en uno, pero no entiendo por qué fallan si se hacen todos a la vez. Parece ser dependiendo del orden en que se ejecuten.

2021-11-05 08:11 UTC, Iker-elorrieta requested changes
Existen libros que se meten por archivo que no cumplen las condiciones al meterlos por teclado.
Los teses se pueden realizar de forma ordenada y preestablecida si el problema es el orden de ejecución.
![image](https://user-images.githubusercontent.com/71759245/140473995-4f461665-a8be-4ccf-8e2e-253aca36b1dd.png)
En algunos la validación aparece y en otros no, (o todos o ninguno)

Se repiten libros en el txt.
![image](https://user-images.githubusercontent.com/71759245/140478675-375e7568-dae2-4b73-93fb-e12f58fab549.png)


¿Para que sirve "Escribir en Txt un libro" ? Si además de hacer lo mismo que incluir el memoria y luego exportar a txt, duplica los datos una y otra vez?

2021-11-08 07:24 UTC, Iker-elorrieta requested changes
![image](https://user-images.githubusercontent.com/71759245/140699700-9430ec2b-9f28-48c9-8f2c-ce26ea413b70.png)
Falla un test

![image](https://user-images.githubusercontent.com/71759245/140699785-db5e7940-d241-49ac-9475-5c7edbabf450.png)

![image](https://user-images.githubusercontent.com/71759245/140700254-8ffc257b-5ddc-494d-812e-39455fcc4db1.png)

Falla en todas las opciones que pongo.

2021-11-08 15:20 UTC, Unai-GarciaGi commented
El test se realiza con TopTestSuite, que va realizando los tests en orden

2021-11-09 07:10 UTC, merged