Sprint3
Iker-elorrieta/ADT1 pull request #3
Opened 2021-11-09 08:40 UTC by Unai-GarciaGi

2021-11-09 12:27 UTC, Iker-elorrieta requested changes
Además de lo comentado el código. 
La funcionalidad no debería quitar el array ni reducirlo. 
Debería no limitar los campos de búsqueda, un buscador para todos los campos.
Solo buscar y mostrar resultados. Buen coverage de test.
Materias deben ser exactas?

2021-11-09 12:27 UTC, Iker-elorrieta commented on AccesoADatos_Reto1/src/buscador/Buscador.java
> +	public ArrayList<Libro> buscarPorTitulo(Scanner sc) {
Las funciones son muy parecidas, deberían de compartir algún método

2021-11-09 12:27 UTC, Iker-elorrieta commented on AccesoADatos_Reto1/src/buscador/Buscador.java
> +			else if(especial.equalsIgnoreCase("i.")) {
FINAL STRING, otra vez

2021-11-09 12:27 UTC, Iker-elorrieta commented on AccesoADatos_Reto1/src/buscador/Buscador.java
> +		ArrayList<Libro> listaFiltrada = new ArrayList<Libro>();
Misma busqueda que por altura

2021-11-09 16:15 UTC, Unai-GarciaGi commented on AccesoADatos_Reto1/src/buscador/Buscador.java
> +	public ArrayList<Libro> buscarPorTitulo(Scanner sc) {
Arreglado, ahora los dos métodos estan fusionados en buscarPorTituloEditorial(Scanner, boolean) que dependiendo del booleano buscará por título (true) o editorial (false)

2021-11-09 16:15 UTC, Unai-GarciaGi commented on AccesoADatos_Reto1/src/buscador/Buscador.java
> +			else if(especial.equalsIgnoreCase("i.")) {
ups, arreglado

2021-11-09 16:16 UTC, Unai-GarciaGi commented on AccesoADatos_Reto1/src/buscador/Buscador.java
> +		ArrayList<Libro> listaFiltrada = new ArrayList<Libro>();
La búsqueda por altura permite números doubles, por eso están separados

2021-11-09 16:52 UTC, Unai-GarciaGi commented
Ahora la funcionalidad no quita el array ni lo reduce, pero permite guardar las búsquedas en un array de búsquedas (funcionalidad para el sprint4, poder ver las búsquedas realizadas)
Ahora hay un buscador para todos los campos de texto
Las materias ahora no son exactas

2021-11-11 07:41 UTC, Iker-elorrieta requested changes
Todas las correcciones ok, excepto el buscador libre, solo busca por texto y a través de contains. Tiene que ser algo más parecido a lo que tenéis con editorial y titulo pero para TODOS los campos, también podría ser algo especial para números pero tiene que ser algo combinable.

2021-11-11 17:46 UTC, Unai-GarciaGi commented
Ahora buscar por texto es buscar general

Si colocas uno de los caracteres especiales (e. i. f.) busca por texto únicamente

Si no, busca en todos los campos

2021-11-12 07:26 UTC, Iker-elorrieta requested changes
![image](https://user-images.githubusercontent.com/71759245/141426929-4a14cfc0-b95d-4b8b-a22f-69a86e1318a5.png)
Se busca por una materia en texto y no aparece.
Busco por texto y tampoco.
![image](https://user-images.githubusercontent.com/71759245/141427166-8492177f-6a47-42f5-980c-9bc8bf5dfc53.png)

2021-11-12 07:55 UTC, Unai-GarciaGi commented
He añadido la clase utilidades, de momento solo imprime listas de libros para no repetir código

Arreglado el error por el cual no se imprimían

2021-11-15 07:33 UTC, merged